name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  WORKING_DIRECTORY: "./angular-monorepo"

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIRECTORY}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "${{env.WORKING_DIRECTORY}}/pnpm-lock.yaml"

      - run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "main"
          working-directory: ${{env.WORKING_DIRECTORY}}

      - name: "Get affected projects"
        id: affected-projects
        run: echo "affected='$(npx nx show projects --affected --sep=' ')'" >> "$GITHUB_OUTPUT"

      - name: "Log affected projects"
        run: echo "${{steps.affected-projects.outputs.affected}}"

      # - run: pnpm exec nx affected -t lint test build
